spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  session: 
    store-type: none
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  queries:
    user-query: select user_id, password, is_active from user where user_id=?
    role-query: select u.user_id, r.role from user u inner join user_roles ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.user_id=?
security:
  basic:
    enabled: false

#server: 
#  context-path: /api
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/health_above_60
    username: healthabove60
    password: healthabove60
    driver-class-name: com.mysql.jdbc.Driver

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/health_above_60
    username: healthabove60
    password: healthabove60
    driver-class-name: com.mysql.jdbc.Driver